$(document).ready(function(){
  $("#st").click(function () {
    $("#go").addClass('go');
    $("#go").removeClass('go_c');
    $(".history_1").addClass('img_op1');
    $(".history_2").addClass('img_op2');
    $(".history_3").addClass('img_op3');
    $(".history_4").addClass('img_op4');
    $(".history_5").addClass('img_op5');
    $(".history_6").addClass('img_op6');
    $(".history_7").addClass('img_op7');
    $(".history_8").addClass('img_op8');
    $(".history_9").addClass('img_op9');
    $(".history_10").addClass('img_op10');
    $(".history_11").addClass('img_op11');
    $(".history_12").addClass('img_op12');
    $(".history_13").addClass('img_op13');
    $(".history_14").addClass('img_op14');
    $(".history_15").addClass('img_op15');
    $(".history_16").addClass('img_op16');
    $(".history_17").addClass('img_op17');
    $(".history_18").addClass('img_op18');
    $(".history_19").addClass('img_op19');
    $(".history_20").addClass('img_op20');
    $(".history_21").addClass('img_op21');
  });
});
